<?php

namespace Acertoin\App;

return [
    ['country' => "Afeganistão", 'capital' => "Cabul"],
    ['country' => "África do Sul", 'capital' => "Pretória"],
    ['country' => "Albânia", 'capital' => "Tirana"],
    ['country' => "Alemanha", 'capital' => "Berlim"],
    ['country' => "Andorra", 'capital' => "Andorra-a-Velha"],
    ['country' => "Angola", 'capital' => "Luanda"],
    ['country' => "Antígua e Barbuda", 'capital' => "Saint John's"],
    ['country' => "Arábia Saudita", 'capital' => "Riade"],
    ['country' => "Argélia", 'capital' => "Argel"],
    ['country' => "Argentina", 'capital' => "Buenos Aires"],
    ['country' => "Armênia", 'capital' => "Erevã"],
    ['country' => "Austrália", 'capital' => "Camberra"],
    ['country' => "Áustria", 'capital' => "Viena"],
    ['country' => "Azerbaijão", 'capital' => "Bacu"],
    ['country' => "Bahamas", 'capital' => "Nassau"],
    ['country' => "Bangladesh", 'capital' => "Daca"],
    ['country' => "Barbados", 'capital' => "Bridgetown"],
    ['country' => "Bahrein", 'capital' => "Manama"],
    ['country' => "Bélgica", 'capital' => "Bruxelas"],
    ['country' => "Belize", 'capital' => "Belmopan"],
    ['country' => "Benim", 'capital' => "Porto Novo"],
    ['country' => "Bielorrússia", 'capital' => "Minsk"],
    ['country' => "Bolívia", 'capital' => "Sucre"],
    ['country' => "Bósnia e Herzegovina", 'capital' => "Sarajevo"],
    ['country' => "Botsuana", 'capital' => "Gaborone"],
    ['country' => "Brasil", 'capital' => "Brasília"],
    ['country' => "Brunei", 'capital' => "Bandar Seri Begawan"],
    ['country' => "Bulgária", 'capital' => "Sófia"],
    ['country' => "Burquina Faso", 'capital' => "Uagadugu"],
    ['country' => "Burundi", 'capital' => "Gitega"],
    ['country' => "Butão", 'capital' => "Timbu"],
    ['country' => "Cabo Verde", 'capital' => "Praia"],
    ['country' => "Camarões", 'capital' => "Iaundé"],
    ['country' => "Camboja", 'capital' => "Phnom Penh"],
    ['country' => "Canadá", 'capital' => "Ottawa"],
    ['country' => "Catar", 'capital' => "Doa"],
    ['country' => "Cazaquistão", 'capital' => "Astana"],
    ['country' => "Chade", 'capital' => "Jamena"],
    ['country' => "Chile", 'capital' => "Santiago"],
    ['country' => "China", 'capital' => "Pequim"],
    ['country' => "Chipre", 'capital' => "Nicósia"],
    ['country' => "Colômbia", 'capital' => "Bogotá"],
    ['country' => "Comores", 'capital' => "Moroni"],
    ['country' => "Coreia do Norte", 'capital' => "Pyongyang"],
    ['country' => "Coreia do Sul", 'capital' => "Seul"],
    ['country' => "Costa do Marfim", 'capital' => "Yamoussoukro"],
    ['country' => "Costa Rica", 'capital' => "São José"],
    ['country' => "Croácia", 'capital' => "Zagrebe"],
    ['country' => "Cuba", 'capital' => "Havana"],
    ['country' => "Dinamarca", 'capital' => "Copenhague"],
    ['country' => "Djibuti", 'capital' => "Djibuti"],
    ['country' => "Dominica", 'capital' => "Roseau"],
    ['country' => "Egito", 'capital' => "Cairo"],
    ['country' => "El Salvador", 'capital' => "San Salvador"],
    ['country' => "Emirados Árabes Unidos", 'capital' => "Abu Dhabi"],
    ['country' => "Equador", 'capital' => "Quito"],
    ['country' => "Eritreia", 'capital' => "Asmara"],
    ['country' => "Eslováquia", 'capital' => "Bratislava"],
    ['country' => "Eslovênia", 'capital' => "Liubliana"],
    ['country' => "Espanha", 'capital' => "Madri"],
    ['country' => "Estado da Palestina", 'capital' => "Jerusalém Oriental"],
    ['country' => "Estados Unidos", 'capital' => "Washington, D.C."],
    ['country' => "Estônia", 'capital' => "Talim"],
    ['country' => "Essuatíni", 'capital' => "Mebabane"],
    ['country' => "Etiópia", 'capital' => "Adis Abeba"],
    ['country' => "Fiji", 'capital' => "Suva"],
    ['country' => "Filipinas", 'capital' => "Manila"],
    ['country' => "Finlândia", 'capital' => "Helsinque"],
    ['country' => "França", 'capital' => "Paris"],
    ['country' => "Gabão", 'capital' => "Libreville"],
    ['country' => "Gâmbia", 'capital' => "Banjul"],
    ['country' => "Gana", 'capital' => "Acra"],
    ['country' => "Geórgia", 'capital' => "Tbilisi"],
    ['country' => "Granada", 'capital' => "Saint George's"],
    ['country' => "Grécia", 'capital' => "Atenas"],
    ['country' => "Guatemala", 'capital' => "Cidade da Guatemala"],
    ['country' => "Guiana", 'capital' => "Georgetown"],
    ['country' => "Guiné", 'capital' => "Conacri"],
    ['country' => "Guiné Equatorial", 'capital' => "Malabo"],
    ['country' => "Guiné-Bissau", 'capital' => "Bissau"],
    ['country' => "Haiti", 'capital' => "Porto Príncipe"],
    ['country' => "Honduras", 'capital' => "Tegucigalpa"],
    ['country' => "Hungria", 'capital' => "Budapeste"],
    ['country' => "Iêmen", 'capital' => "Saná"],
    ['country' => "Ilhas Marshall", 'capital' => "Majuro"],
    ['country' => "Ilhas Salomão", 'capital' => "Honiara"],
    ['country' => "Índia", 'capital' => "Nova Deli"],
    ['country' => "Indonésia", 'capital' => "Jacarta"],
    ['country' => "Irã", 'capital' => "Teerã"],
    ['country' => "Iraque", 'capital' => "Bagdá"],
    ['country' => "Irlanda", 'capital' => "Dublin"],
    ['country' => "Islândia", 'capital' => "Reiquiavique"],
    ['country' => "Israel", 'capital' => "Jerusalém"],
    ['country' => "Itália", 'capital' => "Roma"],
    ['country' => "Jamaica", 'capital' => "Kingston"],
    ['country' => "Japão", 'capital' => "Tóquio"],
    ['country' => "Jordânia", 'capital' => "Amã"],
    ['country' => "Kiribati", 'capital' => "Taraua do Sul"],
    ['country' => "Kuwait", 'capital' => "Cidade do Kuwait"],
    ['country' => "Laos", 'capital' => "Vientiane"],
    ['country' => "Lesoto", 'capital' => "Maseru"],
    ['country' => "Letônia", 'capital' => "Riga"],
    ['country' => "Líbano", 'capital' => "Beirute"],
    ['country' => "Libéria", 'capital' => "Monróvia"],
    ['country' => "Líbia", 'capital' => "Trípoli"],
    ['country' => "Liechtenstein", 'capital' => "Vaduz"],
    ['country' => "Lituânia", 'capital' => "Vilnius"],
    ['country' => "Luxemburgo", 'capital' => "Luxemburgo"],
    ['country' => "Macedônia do Norte", 'capital' => "Escópia"],
    ['country' => "Madagascar", 'capital' => "Antananarivo"],
    ['country' => "Malásia", 'capital' => "Kuala Lumpur"],
    ['country' => "Malaui", 'capital' => "Lilongue"],
    ['country' => "Maldivas", 'capital' => "Malé"],
    ['country' => "Mali", 'capital' => "Bamaco"],
    ['country' => "Malta", 'capital' => "Valeta"],
    ['country' => "Marrocos", 'capital' => "Rabat"],
    ['country' => "Maurícia", 'capital' => "Port Louis"],
    ['country' => "Mauritânia", 'capital' => "Nuaquechote"],
    ['country' => "México", 'capital' => "Cidade do México"],
    ['country' => "Micronésia", 'capital' => "Palikir"],
    ['country' => "Moldávia", 'capital' => "Quixinau"],
    ['country' => "Mônaco", 'capital' => "Mônaco"],
    ['country' => "Mongólia", 'capital' => "Ulan Bator"],
    ['country' => "Montenegro", 'capital' => "Podgorica"],
    ['country' => "Moçambique", 'capital' => "Maputo"],
    ['country' => "Mianmar", 'capital' => "Naypyidaw"],
    ['country' => "Namíbia", 'capital' => "Windhoek"],
    ['country' => "Nauru", 'capital' => "Yaren"],
    ['country' => "Nepal", 'capital' => "Catmandu"],
    ['country' => "Nicarágua", 'capital' => "Manágua"],
    ['country' => "Níger", 'capital' => "Niamei"],
    ['country' => "Nigéria", 'capital' => "Abuja"],
    ['country' => "Noruega", 'capital' => "Oslo"],
    ['country' => "Nova Zelândia", 'capital' => "Wellington"],
    ['country' => "Omã", 'capital' => "Mascate"],
    ['country' => "Países Baixos", 'capital' => "Amsterdã"],
    ['country' => "Palau", 'capital' => "Ngerulmud"],
    ['country' => "Panamá", 'capital' => "Cidade do Panamá"],
    ['country' => "Papua-Nova Guiné", 'capital' => "Port Moresby"],
    ['country' => "Paquistão", 'capital' => "Islamabad"],
    ['country' => "Paraguai", 'capital' => "Assunção"],
    ['country' => "Peru", 'capital' => "Lima"],
    ['country' => "Polônia", 'capital' => "Varsóvia"],
    ['country' => "Portugal", 'capital' => "Lisboa"],
    ['country' => "Quênia", 'capital' => "Nairóbi"],
    ['country' => "Quirguistão", 'capital' => "Bisqueque"],
    ['country' => "República Centro-Africana", 'capital' => "Bangui"],
    ['country' => "República Checa", 'capital' => "Praga"],
    ['country' => "República Democrática do Congo", 'capital' => "Quinxassa"],
    ['country' => "República do Congo", 'capital' => "Brazzaville"],
    ['country' => "República Dominicana", 'capital' => "Santo Domingo"],
    ['country' => "Romênia", 'capital' => "Bucareste"],
    ['country' => "Ruanda", 'capital' => "Quigali"],
    ['country' => "Rússia", 'capital' => "Moscou"],
    ['country' => "Samoa", 'capital' => "Apia"],
    ['country' => "Santa Lúcia", 'capital' => "Castries"],
    ['country' => "São Cristóvão e Neves", 'capital' => "Basseterre"],
    ['country' => "São Marinho", 'capital' => "San Marino"],
    ['country' => "São Tomé e Príncipe", 'capital' => "São Tomé"],
    ['country' => "São Vicente e Granadinas", 'capital' => "Kingstown"],
    ['country' => "Seicheles", 'capital' => "Vitória"],
    ['country' => "Senegal", 'capital' => "Dacar"],
    ['country' => "Serra Leoa", 'capital' => "Freetown"],
    ['country' => "Sérvia", 'capital' => "Belgrado"],
    ['country' => "Singapura", 'capital' => "Singapura"],
    ['country' => "Síria", 'capital' => "Damasco"],
    ['country' => "Somália", 'capital' => "Mogadíscio"],
    ['country' => "Sri Lanka", 'capital' => "Sri Jayawardenepura Kotte"],
    ['country' => "Sudão", 'capital' => "Cartum"],
    ['country' => "Sudão do Sul", 'capital' => "Juba"],
    ['country' => "Suécia", 'capital' => "Estocolmo"],
    ['country' => "Suíça", 'capital' => "Berna"],
    ['country' => "Suriname", 'capital' => "Paramaribo"],
    ['country' => "Tailândia", 'capital' => "Bangcoc"],
    ['country' => "Tajiquistão", 'capital' => "Duxambé"],
    ['country' => "Tanzânia", 'capital' => "Dodoma"],
    ['country' => "Timor-Leste", 'capital' => "Dili"],
    ['country' => "Togo", 'capital' => "Lomé"],
    ['country' => "Tonga", 'capital' => "Nuku'alofa"],
    ['country' => "Trinidad e Tobago", 'capital' => "Port of Spain"],
    ['country' => "Tunísia", 'capital' => "Túnis"],
    ['country' => "Turcomenistão", 'capital' => "Asgabate"],
    ['country' => "Turquia", 'capital' => "Ancara"],
    ['country' => "Tuvalu", 'capital' => "Funafuti"],
    ['country' => "Ucrânia", 'capital' => "Kiev"],
    ['country' => "Uganda", 'capital' => "Campala"],
    ['country' => "Uruguai", 'capital' => "Montevidéu"],
    ['country' => "Uzbequistão", 'capital' => "Tasquente"],
    ['country' => "Vanuatu", 'capital' => "Port Vila"],
    ['country' => "Vaticano", 'capital' => "Cidade do Vaticano"],
    ['country' => "Venezuela", 'capital' => "Caracas"],
    ['country' => "Vietnã", 'capital' => "Hanói"],
    ['country' => "Zâmbia", 'capital' => "Lusaka"],
    ['country' => "Zimbábue", 'capital' => "Harare"],
    ['country' => "Inglaterra", 'capital' => "Londres"],
    ['country' => "Escócia", 'capital' => "Edimburgo"],
    ['country' => "País de Gales", 'capital' => "Cardiff"],
    ['country' => "Irlanda do Norte", 'capital' => "Belfast"],
    ['country' => "Groenlândia", 'capital' => "Nuuk"],
    ['country' => "Porto Rico", 'capital' => "San Juan"],
    ['country' => "Hong Kong", 'capital' => "Hong Kong"],
    ['country' => "Macau", 'capital' => "Macau"],
    ['country' => "Ilhas Faroé", 'capital' => "Tórshavn"],
    ['country' => "Guiana Francesa", 'capital' => "Caiena"],
    ['country' => "Polinésia Francesa", 'capital' => "Papeete"],
    ['country' => "Bermudas", 'capital' => "Hamilton"],
    ['country' => "Gibraltar", 'capital' => "Gibraltar"],
    ['country' => "Aruba", 'capital' => "Oranjestad"],
    ['country' => "Curaçau", 'capital' => "Willemstad"],
    ['country' => "Taiwan", 'capital' => "Taipé"]
];
